min_version = "2025.11.7"

[tools]
bat = "0.26.1"
doggo = "1.1.4"
fd = "10.3.0"
fzf = "0.67.0"
github-cli = "2.86.0"
jj = "0.39.0"
lazygit = "0.61.1"
lsd = "1.2.0"
node = "25.5.0"
ripgrep = "15.1.0"
starship = "1.24.2"
zellij = "0.44.0"
zoxide = "0.9.8"
difftastic = "0.67.0"
"github:twpayne/chezmoi" = "2.70.0"
"github:neovim/neovim" = "0.12.0"

[settings]
experimental = true
lockfile = true
pin = true

[env]
'_'.path = ["~/.cargo/bin"]
'_'.file = { path = ".envrc" }
